module Translations exposing (translate)

import Dict exposing (Dict)

-- THIS FILE WAS AUTO GENERATED BY translations/import.sh



en_ptTranslations = Dict.fromList
    [ ( "********", "TRANSLATION" )
    , ( "(+48) 123 456 789", "TRANSLATION" )
    , ( "Account", "TRANSLATION" )
    , ( "An error occured. Try refreshing the page", "TRANSLATION" )
    , ( "An error occured. Try refreshing your browser", "TRANSLATION" )
    , ( "and you have given TransportApplication permission to use location", "TRANSLATION" )
    , ( "Another user already registered with this email address", "TRANSLATION" )
    , ( "Begin", "TRANSLATION" )
    , ( "Complete", "TRANSLATION" )
    , ( "Confirm", "TRANSLATION" )
    , ( "Delivery destination address input", "TRANSLATION" )
    , ( "Delivery from:", "TRANSLATION" )
    , ( "Delivery is in progress", "TRANSLATION" )
    , ( "Delivery jobs", "TRANSLATION" )
    , ( "Delivery price:", "TRANSLATION" )
    , ( "Delivery to:", "TRANSLATION" )
    , ( "Edit", "TRANSLATION" )
    , ( "Email address", "TRANSLATION" )
    , ( "Email is required", "TRANSLATION" )
    , ( "Entered password is too short - enter at least 5 characters", "TRANSLATION" )
    , ( "Error getting available jobs", "TRANSLATION" )
    , ( "Invalid email", "TRANSLATION" )
    , ( "Invalid phone number", "TRANSLATION" )
    , ( "Invalid state", "TRANSLATION" )
    , ( "Length:", "TRANSLATION" )
    , ( "Loading...", "TRANSLATION" )
    , ( "Login", "TRANSLATION" )
    , ( "Login or register", "TRANSLATION" )
    , ( "Logout", "TRANSLATION" )
    , ( "Menu", "TRANSLATION" )
    , ( "Name", "TRANSLATION" )
    , ( "Name is required", "TRANSLATION" )
    , ( "No drivers are currently available. Your order may take a long time to deliver", "TRANSLATION" )
    , ( "No jobs currently available", "TRANSLATION" )
    , ( "No places found", "TRANSLATION" )
    , ( "Not found", "TRANSLATION" )
    , ( "Not Found", "TRANSLATION" )
    , ( "Order is in progress", "TRANSLATION" )
    , ( "Page not found", "TRANSLATION" )
    , ( "Password", "TRANSLATION" )
    , ( "Password is required", "TRANSLATION" )
    , ( "Phone number", "TRANSLATION" )
    , ( "Phone number is required", "TRANSLATION" )
    , ( "Place an order", "TRANSLATION" )
    , ( "Please enable WebGL support in your browser. See https://get.webgl.org/", "TRANSLATION" )
    , ( "Register", "TRANSLATION" )
    , ( "Request to server has failed", "TRANSLATION" )
    , ( "Reset", "TRANSLATION" )
    , ( "Search", "TRANSLATION" )
    , ( "Select a destination address to continue", "TRANSLATION" )
    , ( "Select delivery destination", "TRANSLATION" )
    , ( "Some features will not work", "TRANSLATION" )
    , ( "Start delivering", "TRANSLATION" )
    , ( "Surname", "TRANSLATION" )
    , ( "Surname is required", "TRANSLATION" )
    , ( "This user does not exist", "TRANSLATION" )
    , ( "To Start:", "TRANSLATION" )
    , ( "To work deliveries, make sure your Location Services are enabled,", "TRANSLATION" )
    , ( "TransportApplication", "TRANSLATION" )
    , ( "You are offline.", "TRANSLATION" )
    , ( "You have entered a bad password", "TRANSLATION" )
    , ( "You have to give TransportApplication permission to use location", "TRANSLATION" )
    , ( "Your order may take up to 3 hours to deliver", "TRANSLATION" )
    , ( "Your order will take a maximum of 30 minutes to deliver", "TRANSLATION" )
    , ( "your@email.com", "TRANSLATION" )
    ]


plTranslations = Dict.fromList
    [ ( "********", "********" )
    , ( "(+48) 123 456 789", "(+48) 123 456 789" )
    , ( "Account", "Konto" )
    , ( "An error occured. Try refreshing the page", "Wystąpił błąd. Spróbuj odświeżyć stronę" )
    , ( "An error occured. Try refreshing your browser", "Wystąpił błąd. Spróbuj odświeżyć przeglądarkę" )
    , ( "and you have given TransportApplication permission to use location", "oraz dałeś TransportApplication uprawnienia do odczytu lokalizacji" )
    , ( "Another user already registered with this email address", "Inny użytkownik już się zarejestrował z tym adresem email" )
    , ( "Begin", "Rozpocznij" )
    , ( "Complete", "Zakończ" )
    , ( "Confirm", "Zatwierdź" )
    , ( "Delivery destination address input", "Pole adresu dostawy" )
    , ( "Delivery from:", "Dostawa z:" )
    , ( "Delivery is in progress", "Dostawa jest w trakcie" )
    , ( "Delivery jobs", "Zlecenia dostawy" )
    , ( "Delivery price:", "Koszt dostawy:" )
    , ( "Delivery to:", "Dostawa do:" )
    , ( "Edit", "Edytuj" )
    , ( "Email address", "Adres email" )
    , ( "Email is required", "Adres email jest wymagany" )
    , ( "Entered password is too short - enter at least 5 characters", "Wprowadzone hasło jest za krótkie - wprowadź przynajmniej 5 znaków" )
    , ( "Error getting available jobs", "Wystąpił błąd podczas ładowania dostępnych zadań" )
    , ( "Invalid email", "Nieprawidłowy email" )
    , ( "Invalid phone number", "Nieprawidłowy numer telefonu" )
    , ( "Invalid state", "Nieprawidłowy stan" )
    , ( "Length:", "Długość:" )
    , ( "Loading...", "Ładowanie..." )
    , ( "Login", "Zaloguj" )
    , ( "Login or register", "Logowanie lub rejestracja" )
    , ( "Logout", "Wyloguj się" )
    , ( "Menu", "Menu" )
    , ( "Name", "Imię" )
    , ( "Name is required", "Imię jest wymagane" )
    , ( "No drivers are currently available. Your order may take a long time to deliver", "Nie ma aktualnie dostępnych dostawców. Twoje zamówienie może być dostarczane przez długi czas" )
    , ( "No jobs currently available", "Nie ma aktualnie dostępnych zadań" )
    , ( "No places found", "Nie znaleziono miejsc" )
    , ( "Not found", "Nie znaleziono" )
    , ( "Not Found", "Nie znaleziono" )
    , ( "Order is in progress", "Dostawa jest w trakcie realizacji" )
    , ( "Page not found", "Strona nie znaleziona" )
    , ( "Password", "Hasło" )
    , ( "Password is required", "Hasło jest wymagane" )
    , ( "Phone number", "Numer telefonu" )
    , ( "Phone number is required", "Numer telefonu jest wymagany" )
    , ( "Place an order", "Złóż zamówienie" )
    , ( "Please enable WebGL support in your browser. See https://get.webgl.org/", "Włącz obsługę WebGL w przeglądarce. Zobacz https://get.webgl.org/" )
    , ( "Register", "Zarejestruj" )
    , ( "Request to server has failed", "Żądanie do serwera zakończone niepowodzeniem" )
    , ( "Reset", "Resetuj" )
    , ( "Search", "Szukaj" )
    , ( "Select a destination address to continue", "Wybierz adres dostawy, aby kontynuować" )
    , ( "Select delivery destination", "Wybierz adres dostawy" )
    , ( "Some features will not work", "Niektóre funkcje nie będą działać" )
    , ( "Start delivering", "Rozpocznij dostawy" )
    , ( "Surname", "Nazwisko" )
    , ( "Surname is required", "Nazwisko jest wymagane" )
    , ( "This user does not exist", "Ten użytkownik nie istnieje" )
    , ( "To Start:", "Do rozpoczęcia:" )
    , ( "To work deliveries, make sure your Location Services are enabled,", "Aby dostarczać zamówienia, upewnij się że włączone są usługi lokalizacyjne," )
    , ( "TransportApplication", "TransportApplication" )
    , ( "You are offline.", "Jesteś offline." )
    , ( "You have entered a bad password", "Złe hasło" )
    , ( "You have to give TransportApplication permission to use location", "Musisz dać TransportApplication uprawnienia do usług lokalizacyjnych" )
    , ( "Your order may take up to 3 hours to deliver", "Twoje zamówienie może być dostarczane przez maksymalnie 3 godziny" )
    , ( "Your order will take a maximum of 30 minutes to deliver", "Twoje zamówienie może być dostarczane przez maksymalnie 30 minut" )
    , ( "your@email.com", "twoj@email.pl" )
    ]








allLanguages = Dict.fromList
    [ ( "pl", plTranslations )
    , ( "en_pt", en_ptTranslations )
    ]


translate : String -> String -> String
translate lang key =
    case Dict.get lang allLanguages of
        Just values ->
            case Dict.get key values of
                Just value -> value
                Nothing -> "MISSING TRANSLATION"
        Nothing -> key

