#! /usr/bin/env bash

rootdir=$(realpath "$(dirname "$0")/../")
langs=( 'pl' 'en_pt' )

translationdicts=""

for lang in ${langs[@]}; do
    translationdicts="
${lang}Translations = Dict.fromList
$(cat "${rootdir}/translations/${lang}.translation" | \
awk -F '|' '{ gsub(/[ \t]+$/,"",$1); gsub(/^[ \t]+/,"",$2); } NR==1 { printf "    [ ( \"%s\", \"%s\" )\n",  $1, $2; } NR!=1 { printf "    , ( \"%s\", \"%s\" )\n",  $1, $2; }')
    ]

${translationdicts}

"
done

translationindex="    [ ( \"${langs[0]}\", ${langs[0]}Translations )"

for lng in ${langs[@]:1}; do
    translationindex="${translationindex}
    , ( \"$lng\", ${lng}Translations )"
done

cat << EOF > $rootdir/src/Translations.elm
module Translations exposing (translate)

import Dict exposing (Dict)

-- THIS FILE WAS AUTO GENERATED BY translations/import.sh


${translationdicts}


allLanguages = Dict.fromList
${translationindex}
    ]


translate : String -> String -> String
translate lang key =
    case Dict.get lang allLanguages of
        Just values ->
            case Dict.get key values of
                Just value -> value
                Nothing -> "MISSING TRANSLATION"
        Nothing -> key

EOF
